const mongoose = require('mongoose');

const LoanSchema = new mongoose.Schema({
  LoanNumber: String,
  Name: String,
  cusfname: String,
  cussname: String,
  guafname: String,
  guasname: String,
  cusdob: Date,
  guadob: Date,
  cusgen: String,
  guagen: String,
  cusmob: Number,
  guamob: Number,
  cusadd: String,
  guaadd: String,
  guaaadhaar: String,
  cusaadhaar: String,
  nomineeName: String,
  nomineeAadhar: String,
  Date: Date,
  Amount: Number,
  purpose: String,
  Tenure: Number,
  Type: String,
  interest: Number,
  principal: Number,
  fee: Number,
  gst: Number,
  cibilCharge: Number,
  servicecharge: Number,
  advance: Number,
  EMI: Number,
  balanceamount: Number,
  collectedamount: Number,
  Notes: String,
  paid_from: String,
  status: Number,
  cusid: String,
  flag: Number,
  fileno: String,
  guacibil: Number,
  cuscibil: Number,
  collectInitialPayment: String,
  collectionOption: String,
  collectionText: String,
  disbursalOption: String,
  chargeOption: String,
  chargeDebitOption: String,
  feeOption: String,
  gstOption: String,
  cibilOption: String,
  emiDay: Number,
  adjustmentAmount: Number,
  staffAmount: Number,
  cashierAmount: Number,
  bankAmount: Number,
  approvalDate: Date,
  groupid: String,
  relation: String,
  totalValue: Number,
  eligibleAmount: Number,
  ornaments: [{
    ornamentType: String,
    netWeight: Number,
    grsWeight: Number,
    purity: String,
    remark: String
  }],
  image: {
    data: String,
    contentType: String,
    size: Number,
    imageDriveId: String,
    imageLink: String
  }
}, { 
  collection: 'pending_loan',
  timestamps: true 
});

module.exports = mongoose.model('PendingLoan', LoanSchema); 